version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      "/"
      "/docker/base-images"
    schedule:
      interval: "daily"
