name: 'Trivy Action'
description: 'Run Trivy vulnerability scanner'

inputs:
  image-tags:
    required: true
    type: string
  image-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set variables
      env:
        TAGS: ${{ inputs.image-tags }}
        NAME: ${{ inputs.image-name }}
      id: vars
      shell: bash
      run: |
        tag=$(echo "$TAGS" | head -1)
        name=${NAME// /-}
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "name=${name}" >> $GITHUB_OUTPUT

    - name: Scan Container Image
      id: scan
      uses: aquasecurity/trivy-action@0.32.0
      with:
        cache: true
        exit-code: 0
        image-ref: ${{ steps.vars.outputs.tag }}
        format: 'table'
        output: 'trivy-${{ steps.vars.outputs.name }}-results.sarif'

    # - name: Upload ${{ inputs.image-name }} image Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   #if: always()
    #   with:
    #     sarif_file: 'trivy-${{ steps.vars.outputs.name }}-results.sarif'
    #     category: trivy-${{ steps.vars.outputs.name }}-results
