name: 'Trivy Action'
description: 'Run Trivy vulnerability scanner'

inputs:
  image-tags:
    required: true
    type: string
  image-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set variables
      env:
        TAGS: ${{ inputs.image-tags }}
        NAME: ${{ inputs.image-name }}
      id: vars
      shell: bash
      run: |
        tag=$(echo "$TAGS" | head -1)
        name=${NAME// /-}
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "name=${name}" >> $GITHUB_OUTPUT
      
    - name: Install ORAS
      id: oras
      uses: oras-project/setup-oras@v1

    - name: Authenticate to GHCR
      env:
        PW: ${{ github.token }}
      id: ghcr
      shell: bash
      run: echo "$PW" | oras login ghcr.io -u github-actions --password-stdin

    - name: Pull Trivy DBs from GHCR
      id: pull
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/.cache/trivy/db
        oras pull ghcr.io/temporalio/trivy-db:2
        tar -xzf db.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/db
        rm db.tar.gz

        mkdir -p $GITHUB_WORKSPACE/.cache/trivy/java-db
        oras pull ghcr.io/temporalio/trivy-java-db:1
        tar -xzf javadb.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/java-db
        rm javadb.tar.gz

    - name: Scan Container Image
      id: scan
      uses: aquasecurity/trivy-action@0.32.0
      env:
        TRIVY_SKIP_DB_UPDATE: true
        TRIVY_SKIP_JAVA_DB_UPDATE: true
      with:
        cache: true
        exit-code: 0
        image-ref: ${{ steps.vars.outputs.tag }}
        format: 'table'
        output: 'trivy-${{ steps.vars.outputs.name }}-results.sarif'

    # - name: Upload ${{ inputs.image-name }} image Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   #if: always()
    #   with:
    #     sarif_file: 'trivy-${{ steps.vars.outputs.name }}-results.sarif'
    #     category: trivy-${{ steps.vars.outputs.name }}-results
