name: 'Trivy Action'
description: 'Run Trivy vulnerability scanner'

inputs:
  image-tags:
    required: true
    type: string
  image-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set variables
      env:
        TAGS: ${{ inputs.image-tags }}
        NAME: ${{ inputs.image-name }}
      id: vars
      shell: bash
      run: |
        tag=$(echo "$TAGS" | head -1)
        name=${NAME// /-}
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "name=${name}" >> $GITHUB_OUTPUT

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.3
      with:
        version: v0.65.0

    - name: Scan Container Image
      id: scan
      shell: bash
      run: |
        echo "Scanning image: ${{ steps.vars.outputs.tag }}" 
        echo "Image name: ${{ steps.vars.outputs.name }}"
        trivy image --severity HIGH,CRITICAL --exit-code 0 --no-progress ${{ steps.vars.outputs.tag }}

    # - name: Upload ${{ inputs.image-name }} image Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   #if: always()
    #   with:
    #     sarif_file: 'trivy-${{ steps.vars.outputs.name }}-results.sarif'
    #     category: trivy-${{ steps.vars.outputs.name }}-results
